spring.application.name=springboot-test-demo
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mariadb://localhost:3306/unit_test_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=#De123456789.
spring.jpa.database-platform=org.hibernate.dialect.MariadbDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect